### ISSUE TITLE
Getting `com.facebook.react.bridge.ReactApplicationContext cannot be cast to android.app.Activity` error when upgrading to the latest version 1.6.1

### ISSUE THREAD

**Issue by rubina-shakhkyan** [verygoodsecurity/vgs-collect-android#137]
**Describe the bug**
When upgrading to the latest(1.6.1) version  in a RN application I get the following error:
com.facebook.react.bridge.ReactApplicationContext cannot be cast to android.app.Activity

**To Reproduce**

Integrate the 1.6.1 version in the sample React Native application 
(https://github.com/verygoodsecurity/vgs-collect-android-react-native)

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - SDK Version 1.6.1
 - Android Version: 10.0
 - Device: Pixel3a_ Api_30_x86
 - Target sdk version 29

**Additional context**

**Possible Solution**
Adding a try-catch block when casting context to activity.

**Comment by Endorf** [comment]
Thank you for the issue. We are investigating it.

**Comment by Endorf** [comment]
Hi @rubina-shakhkyan ! We have already updated [React Native example](https://github.com/verygoodsecurity/vgs-collect-android-react-native) to the latest version of VGS Collect SDK. Please pull changes from the master branch.

In case you have any questions let us know.

**Comment by rubina-shakhkyan** [comment]
Thank you! All fixed.
