### ISSUE TITLE
Minor issues in documentation & migration

### ISSUE THREAD

**Issue by mikkoville** [verygoodsecurity/vgs-collect-android#175]
**Describe the bug**
Not sure if this is right repo to reports issues in docs but here goes

I migrated from `vgscollect:1.2.4` to `vgscollect:1.6.6` and hit a build error with missing `app:fieldType="cvc"` on our `VGSEditText`. Seems it is gone in favor of new component `CardVerificationCodeEditText`. This took me a while to figure out since there was still in the `VGSEditText` [docs](https://www.verygoodsecurity.com/docs/vgs-collect/android-sdk/vgs-edit-text#additional-xml-attributes) mention it supports `app:fieldType`. 

Also the [main doc page showcasing the components says](https://www.verygoodsecurity.com/docs/vgs-collect/android-sdk/ui-components#cardverificationcodeedittext) that `CardVerificationCodeEditText` is "Provides a user interface element that represents a person's name." 

**To Reproduce**
1. Check links to documentation

**Expected behavior**
Would be also nice to have in the release notes a clear mention if a property is remove / replaced in a new version

Thanks

**Comment by Endorf** [comment]
@mikkoville Thank you for this issue. We will update the documentation with our migration guide.

This is correct that you should use CardVerificationCodeEditText instead of VGSEditText with app:fieldType="cvc" attribute.

**Comment by Endorf** [comment]
We updated our docs. Also, we mentioned those changes in the migration guide and release notes.

**Comment by mikkoville** [comment]
Thanks a lot!
