### ISSUE TITLE
Version 1.6.7 VGSEditText can not display password type input

### ISSUE THREAD

**Issue by theerasan** [verygoodsecurity/vgs-collect-android#185]
**Describe the bug**
VGSEditText on vgs-collect-android version 1.6.7 validation not working inputType attribute not working

**To Reproduce**
1.  Go to xml file and add VGSEditText
`
<com.verygoodsecurity.vgscollect.widget.VGSEditText
        android:id="@+id/editText"
        app:inputType="numberPassword"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"/>
`
Go to activity add code like this 
        

        val pin = findViewById<VGSEditText>(R.id.editText)

        pin.enableValidation(true)
        pin.setMaxLength(6)`
2. Run the app, its turn out `editText` display as normal EditText also can input alphabet validation not working

**Expected behavior**
Should show the password
Input should accept only number

**Screenshots**
<img width="1702" alt="Screen Shot 2564-06-04 at 16 04 20" src="https://user-images.githubusercontent.com/27719931/120776664-ad447d80-c54e-11eb-8d9c-bc8ab58946d6.png">

**Environment (please complete the following information):**
 - SDK Version 1.6.7
 - Android Version: [Api 28]
 - Device: [e.g. Emulator Pixel 2]

**Comment by Endorf** [comment]
Hello @theerasan
Thank you for informing us about this issue.
We will have a look at this.

**Comment by Endorf** [comment]
We have already released version 1.6.8 with the fix. 
Also, I want to highlight that `setMaxLength` works as [android:maxLength](https://developer.android.com/reference/android/widget/TextView.html#attr_android:maxLength) android attribute. This method limits the max length of the field. To specify custom validation rules please use [VGSInfoRule.ValidationBuilder](https://www.verygoodsecurity.com/docs/vgs-collect/android-sdk/info-field-validation-rules).

**Comment by jai** [comment]
I think we're also seeing issues on the ValidationRule builder is that correct @theerasan @aung @tuinui?

**Comment by theerasan** [comment]
@aungThiha ⬆️

**Comment by AungThiha** [comment]
@jai @theerasan VGSInfoRule works. I got the answer here.
https://github.com/verygoodsecurity/vgs-collect-android/issues/189
