### ISSUE TITLE
VGSInfoRule doesn't work with VGSEditText

### ISSUE THREAD

**Issue by AungThiha** [verygoodsecurity/vgs-collect-android#189]
VGSInfoRule doesn't work

**To Reproduce**
1. add this code
```
val rule : VGSInfoRule = VGSInfoRule.ValidationBuilder()
    .setRegex("(?!0{6})(?!1{6})(?!2{6})")
    .setAllowableMinLength(6)
    .setAllowableMaxLength(6)
    .build()

vgsEditTextPin.addRule(rule)

vgsEditTextPin.setOnFieldStateChangeListener(object : OnFieldStateChangeListener {
    override fun onStateChange(state: FieldState) {
        Log.d("VGS", "valid: ${state.isValid}")
    }
})
```
2. enter "123456"
3. see the log
4. `state.isValid` is `false`

**Expected behavior**
`state.isValid` should be `true` at step 4

**Environment**
 - SDK Version: 1.6.8
 - Android Version: 11
 - Device: Galaxy S20

**Comment by AungThiha** [comment]
sorry, forgot one thing.
The doc is also not updated. I cannot find `VGSInfoValidationRule` but the doc mentions it.
I can only find `VGSInfoRule` from the sdk.
https://www.verygoodsecurity.com/docs/vgs-collect/android-sdk/vgs-edit-text

**Comment by Endorf** [comment]
Thank you for mentioning mistakes in documentations! They will be fixed.

Regarding the issue with validation rules, please check if your regex is correct. Without `setRegex` rule - behaviour is as expected.

**Comment by AungThiha** [comment]
Thanks, @Endorf 
You're right. It's because of the regex.
