### ISSUE TITLE
Regex Negative Pattern for VGSInfoRule

### ISSUE THREAD

**Issue by AungThiha** [verygoodsecurity/vgs-collect-android#190]
**Is your feature request related to a problem? Please describe.**
Right now, the VGSInfoRule can mark the input valid only when the input matches the regex.

**Describe the solution you'd like**
I want the input to be valid when the input doesn't match the regex.
That will make it easy to set regex to reject invalid input.

**Example**
With this, `111111` should be invalid.
```
val rule : VGSInfoRule = VGSInfoRule.ValidationBuilder()
    .setNegativeRegex("^([0-9])\1{5,}$")
    .setAllowableMinLength(6)
    .setAllowableMaxLength(6)
    .build()
```

**Describe alternatives you've considered**
A very long regex with a negative pattern

**Comment by Endorf** [comment]
I guess you need [Negative Lookahead](https://www.regular-expressions.info/lookaround.html). 
The regex should be like this - `^((?!REGEX).)*$`. According to mentioned earlier example - `^((?!([0-9])\1{5,}).)*$`.

You can play with it on this [site](https://regex101.com/r/CuICg5/1).

**Comment by AungThiha** [comment]
Thanks for the help. I tried it. `478952` should match since all the digits are not the same number but it doesn't match `^((?!([0-9])\1{5,}).)*$`.

Understood that it's possible to create a negative pattern without having something like `.setNegativeRegex` from the sdk but it would be easier for the users of the sdk if it supports it.

**Comment by Endorf** [comment]
It makes sense. Thanks for the feedback.
