### ISSUE TITLE
Keyboard doesn't show up after bringing the app back from background

### ISSUE THREAD

**Issue by AungThiha** [verygoodsecurity/vgs-collect-android#191]
**Describe the bug**
Soft Keyboard doesn't show up after bringing the app back from background

**To Reproduce**
1. tap the edittext
2. tap device back button
3. tap device home button
4. tap task manager button of the device and choose the app
5. tap the edittext
6. no keyboard shows up

**Expected behavior**
Keyboard should show up at step 6

**Recorded video**
https://user-images.githubusercontent.com/4388183/121234566-09483280-c8be-11eb-978c-95c40e684e18.mov

**Environment (please complete the following information):**
 - SDK Version 1.6.8
 - Android Version: 11
 - Device: Samsung Galaxy S20

**Comment by Endorf** [comment]
Thank you for informing us about this issue.
We will have a look at this.

**Comment by Endorf** [comment]
Hi @AungThiha. 
We released a new version of VGS Collect SDK `v1.6.9` with fix to this bug.

**Comment by AungThiha** [comment]
Thanks for the fix. Will try it out.
