### ISSUE TITLE
Null value for VGSResponse.ErrorResponse rawResponse

### ISSUE THREAD

**Issue by boroslorena** [verygoodsecurity/vgs-collect-android#284]
After I submit invalid card data (for example: cardType of newly added card is CREDIT, but only DEBIT is supported on the backend) to the VGS proxy (VGS server) by calling `vgsCollect.submit(cardData))`, I get VGSResponse.ErrorResponse with appropriate errorCode value, but the value for body is null (for rawResponse as well).
But, if I send the same request via Postman, I can see errorBody with appropriate message. I also see correct value for error body on VGS dashboard. So, as it seems, for some reason VGS proxy ignores error body sent by backend and returns null value. 

Expected behaviour would be to get VGSResponse.ErrorResponse with appropriate errorCode value and raw response and/or errorBody with error message sent from backend.

Here is a screenshot of response I receive.
![VGS](https://user-images.githubusercontent.com/56020685/139079487-471fa36e-25de-4ce1-8026-a97d7511af9b.png)

Environment
 - SDK Version: VGS collect = 1.6.11
 - Android Version: 11
 - Device: Samsung S21 Ultra

**Comment by Endorf** [comment]
Hi, @boroslorena
Please check our latest version of VGS Collect SDK v1.6.16. This behavior is fixed there.

**Comment by boroslorena** [comment]
Awesome. Updated the SDK and everything works fine.
