### ISSUE TITLE
Request authentication

### ISSUE THREAD

**Issue by shchurov** [verygoodsecurity/vgs-collect-android#34]
We're using a mix of okhttp3 Interceptor and Authenticator to do the authentication for our requests (adding headers, refreshing tokens, handling 401 response etc.)
Is there any recommended approach on how to do it with VGSCollect?
Perhaps you can extend your API so that consumer code has an option to attach custom Interceptors and Authenticators to your OkHttpClient?

**Comment by Endorf** [comment]
We are using the approach that is based on untouchable final-user data by implementors. Also, our  SDK doesn’t require authentification.
As for responses, refreshing tokens, error handling, etc. - You may cover it by response listener. You may find how to do it [here](https://www.verygoodsecurity.com/docs/vgs-collect/android-sdk/submit-data#handling-responses).
The best practice for Collect SDK is to interacts with the payment screen only. Please see our [Demo application](https://github.com/verygoodsecurity/android-sdk-demo)

**Comment by shchurov** [comment]
Hey @Endorf 👋
Correct me if I'm wrong, but VGS will then send the data to our servers on behalf of the user. 
Our backend API uses OAuth 2 and expects `Authorization` header in the request. In certain cases it might also return 401 error response requiring the app to refresh the auth token. This whole process is quite standard and used by many apps but requires some amount of logic (including some tricky concurrency stuff).
OkHttp makes life easier by providing handy request interceptors. Do you plan to add anything similar to your API? I believe it's a common problem for many apps.

**Comment by Endorf** [comment]
If I understand correctly - you are using okHTTP + interceptors for handling all HTTP requests in one place?
Unfortunately, we can't let passing data from VGSCollect fields through third-party's functions because they contain sensitive data, and these functions can touch sensitive data.
If it happens - you will be out of PCI Scope.
Due to the fact that we have to follow the regulations, all what we can allow: its attach additional data and headers to request and handle the response in the callback.

such kind of flow you can add your header and submit
```
val headers = HashMap<String, String>()
headers["CUSTOM-HEADER"] = "custom-value"
val request: VGSRequest = VGSRequest.VGSRequestBuilder()
            .setMethod(HTTPMethod.POST)
            .setPath("/path")
            .setCustomHeader(headers)
            .build()
vgsCollect.asyncSubmit(request)
```
or handle response errors:
```
vgsCollect.addOnResponseListeners(object : VgsCollectResponseListener {
        override fun onResponse(response: VGSResponse?) {
               when(response.code) {
                      401 -> handleError()
                      402 -> handleError()
               }
        }
}
```

**Comment by shchurov** [comment]
Just to clarify, don't you do client-side data encryption before sending it?

**Comment by Endorf** [comment]
VGS Proxy accepts only HTTPS(TLS) requests and you can set up a proxy for encrypting sensitive data before they arrive at your BE.
In the client-side additional encryption case, you greatly increase the complexity of integration. Also, we never store sensitive information in phone memory after a user sent data to your side.
Our Proxy Server has strong encryption (we utilize AES 256) with segregated accounts, key rotation, patch management, etc.. You could find this [here](https://www.verygoodsecurity.com/docs/guides/vault#why-is-it-important).
Using HTTPS + VGS Proxy cover all PIC scope cases.

**Comment by shchurov** [comment]
Got it, thanks for the detailed answer!
