### ISSUE TITLE
How can I send extraData as ios-sdk does.

### ISSUE THREAD

**Issue by Great-hijack** [verygoodsecurity/vgs-collect-android#362]
**Is your feature request related to a problem? Please describe.**
How can I send extraData as ios-sdk does.

![image](https://user-images.githubusercontent.com/57619523/157884805-dfee5bbc-62e2-42a6-8809-902de3b5d153.png)

As can see below, asyncSubmit doesn't have any params for extraData.
![image](https://user-images.githubusercontent.com/57619523/157884992-9de3b6a8-f1d1-41ac-bbfd-d09a90f11e3f.png)

I want to send additional data with sensitive data.
Need help on this problem.

**Comment by Endorf** [comment]
Hi @Great-hijack. 
VGS Collect SDK allows setting additional data by using `VGSRequestBuilder`. You can find this information in the [following section](https://www.verygoodsecurity.com/docs/vgs-collect/android-sdk/android-custom-data#dynamic-data).

**Comment by Great-hijack** [comment]
@Endorf  Thanks a lot!
To be honest, I didn't know that, but it would be more helpful if you can add an example to the demo repo.

**Comment by Endorf** [comment]
This example shows how to add additional data:
```
fun submitData() {
    val customData = HashMap<String, Any>()
    customData.put("nonSDKValue", "value")

    val request: VGSRequest = VGSRequest.VGSRequestBuilder()
                .setMethod(HTTPMethod.POST)
                .setPath(path)
                .setCustomData(customData)
                .ignoreFiles()
                .ignoreFields()
                .build()

    vgsForm.asyncSubmit(request)
}
```

Also, [here](https://github.com/vgs-samples/vgs-collect-show-android-react-native-demo) you can find simple implementation of possible application.
