### ISSUE TITLE
Custom card brand icons

### ISSUE THREAD

**Issue by shchurov** [verygoodsecurity/vgs-collect-android#37]
We noticed that iOS SDK provides API for setting custom card brand icons: https://www.verygoodsecurity.com/docs/vgs-collect/ios-sdk/ui-components#setting-custom-card-brand-images

I can't find anything similar in Android SDK. Do you have any plans on adding this feature?

**Comment by Endorf** [comment]
We are working on adding this feature to our Android SDK as well, and you will be able to get it in the nearest releases.
