### ISSUE TITLE
Only last rule added to text field is checked

### ISSUE THREAD

**Issue by shaneboyar** [verygoodsecurity/vgs-collect-android#399]
**Describe the bug**
Given a `VGSEditText` instance, only the last in a set of multiple regex validations added using `.addRule` is used to validate the input's content.

**To Reproduce**
1. Create a `VGSEditText` instance: `val editText = VGSTextEdit(...)`
2. Create a rule that uses a regex to check that the input is 4 non-repeating digits:
```
 val vgsValidatorRepeating =
  VGSInfoRule.ValidationBuilder()
    .setRegex("^(?!0000|1111|2222|3333|4444|5555|6666|7777|8888|9999)\\d{4}\$")
    .build()
```
3. Create a rule that uses a regex to check that the input is 4 non-consecutive digits:
```
 val vgsValidatorConsec = 
  VGSInfoRule.ValidationBuilder()
    .setRegex("^(?!0123|1234|2345|3456|4567|5678|6789|7890|0987|9876|8765|7654|6543|5432|4321)\\d{4}\$")
     .build()
```
4. Add the rules to your `VGSTextEdit` instance
```
editText.addRule(vgsValidatorRepeating)
editText.addRule(vgsValidatorConsec)
```
6. Input Repeating set of numbers eg: "1111", check input state, and see `InputState.isValid = true`
7. Input Consecutive set of numbers eg "1234", check input state and see `InputState.isValid = false`
8. Swap order of rules in step 4, and redo steps 6 and 7, but notice the validity is reversed.

**Expected behavior**
Both regex rules should be applied to the input and therefore, in this case, either a consecutive OR a repeating input should be invalid.

**Environment (please complete the following information):**
 - SDK Version [e.g. 1.7.0]
 - Android Version: [e.g. 12.0 \ Snow Cone]
 - Device: [e.g. Pixel 4 (Android Studio Emulator)]

**Comment by DmytroDm** [comment]
@shaneboyar Thank you for your report. We currently working on this feature, and we will notify you soon about updates.

**Comment by DmytroDm** [comment]
@shaneboyar We have released a new version, 1.7.1, containing fixes related to your request. In the latest release we marked `addRule` as a deprecated function, so starting from v1.7.1 if you want to add a rule you need to call `appendRule` function, and if you want to replace rules you should use `setRule/setRules`.  Check release [notes](https://github.com/verygoodsecurity/vgs-collect-android/releases/tag/v1.7.1) for more updates.

**Comment by shaneboyar** [comment]
Updating to the new version now, thanks!

**Comment by shaneboyar** [comment]
This appears to be working. Thanks!
