### ISSUE TITLE
VGSInfoRule is ignored for VgsEditText

### ISSUE THREAD

**Issue by marcoRS** [verygoodsecurity/vgs-collect-android#413]
**Describe the bug**
Hello, I am trying to add a rule to a VgsEditText to restrict user input to 4 digits using the following: 
```kotlin
val lengthValidator = VGSInfoRule.ValidationBuilder().apply {
            setRegex("^[0-9]{4}\$")
            setAllowableMaxLength(4)
            setAllowableMinLength(4)
            }
                .build()

        pinEntryEditText.setRule(lengthValidator)
```

**To Reproduce**
Add a rule to VgsEditText as seen in the description. 

**Expected behavior**
I was expecting the user to only be allowed to enter a max length 4 digit number pin into the VgsEditText however I am able to enter a pin that is not restricted by length.  
**Environment (please complete the following information):**
Pixel 4 Api 29 using Vgs Collect Sdk 1.7.1
**Additional context**

**Possible Solution**
Either the regex may not be correct or setup is incorrect. Possibly the SDK has a bug.

**Comment by marcoRS** [comment]
Hello I also had a related question to this rule setting. I am trying to implement a UI where a user can input a 4 digit card `PIN` and my team would like to compare the input of two EditText fields to make sure the user entered the same PIN. 

Is this possible with a `VGSInfoRule` ? It appears we are not able to make this type of comparison or I cannot find it in the api docs. Thanks!

<img width="274" alt="Screen Shot 2022-08-29 at 7 40 55 PM" src="https://user-images.githubusercontent.com/507510/187336658-8195dccb-20c8-45e4-a4a6-2dd6f4882f5a.png">

**Comment by DmytroDm** [comment]
@marcoRS HI, `VGSInfoRule` validates user input, it does not limit it. If you want to limit  input to max 4 characters, you should use `pinEntryEditText.setMaxLength(4)`.

Currently, it's not possible to compare input fields using `VGSInfoRule`. You can do it using `VGSEditText.isContentEquals(VGSEditText)` function. Depending on your case, you can do it inside the `OnTextChangedListener.onTextChange`.

**Comment by marcoRS** [comment]
Great that makes sense. Thanks!
