### ISSUE TITLE
Is AGP 8.x.x changes to R8 taken into account already?

### ISSUE THREAD

**Issue by mikkoville** [verygoodsecurity/vgs-collect-android#563]
This is more of a question than a feature request.

Does VGS sdk already take into account breaking changes introduced in AGP 8.x.x ?

Most notably how R8 now works since it has` android.enableR8.fullMode` as `true` by default?
https://developer.android.com/build/releases/past-releases/agp-8-0-0-release-notes#default-changes

We have seen many of our 3rd party sdks crashing for R8 issues when we tried the update some months ago.

Here is one example by Adyen: https://github.com/Adyen/adyen-3ds2-android/issues/53

So does VGS already support new more strict proguard rules or do we need to wait for new release?

Thanks

**Comment by DmytroDm** [comment]
@mikkoville Hi, yes, we already added [proguard-rules.pro](https://github.com/verygoodsecurity/vgs-collect-android/blob/master/vgscollect/proguard-rules.pro), so no need to wait for new release.
