### ISSUE TITLE
VGSCardNumberEditText scrumbles digits order

### ISSUE THREAD

**Issue by abaryzhikov** [verygoodsecurity/vgs-collect-android#604]
Hello,

there's an issue with `VGSCardNumberEditText` that scrumbles the order of digits when editing card number.

It happens because of the full input string replacement in `CardNumberFormatter` [here](https://github.com/verygoodsecurity/vgs-collect-android/blob/1771724453948406059662db0e0dff47b09117bf/vgscollect/src/main/java/com/verygoodsecurity/vgscollect/view/card/formatter/CardNumberFormatter.kt#L26C19-L26C19)

Possible fix is editing the string on character level (deleting/inserting characters) instead of replacing the whole thing. It will keep the correct cursor position.

https://github.com/verygoodsecurity/vgs-collect-android/assets/110050067/0ead0fad-4446-4a5f-aefe-40ac5edd53ca

**Comment by DmytroDm** [comment]
@abaryzhikov Hi, thank you for the details, I will take a look.

**Comment by DmytroDm** [comment]
@abaryzhikov Hi, the issue is fixed in the latest release, check release notes please https://github.com/verygoodsecurity/vgs-collect-android/releases/tag/v1.8.4
