### ISSUE TITLE
Made Composable compatible with fragment

### ISSUE THREAD

**Issue by NachoAstro** [verygoodsecurity/vgs-collect-android#627]
**Is your feature request related to a problem? Please describe.**
We can't render the previews with the latest version (1.9.0 Compose compatible) in Fragments, only in Activities

**Describe the solution you'd like**
Be compatible with fragments

**Describe alternatives you've considered**
We tried several workarounds but no luck

**Additional context**
Attached problem log
[preview_error.txt](https://github.com/verygoodsecurity/vgs-collect-android/files/14142257/preview_error.txt)

**Comment by DmytroDm** [comment]
Thank you for informing us about this issue.
We will have a look at this.

**Comment by DmytroDm** [comment]
Hi @NachoAstro, which theme do you use for your app or activity which contains fragment?

**Comment by NachoAstro** [comment]
MaterialTheme

**Comment by DmytroDm** [comment]
@NachoAstro Can you reproduce same issue on our demo project?

**Comment by NachoAstro** [comment]
Yes. in you demo project you only use Activity

**Comment by DmytroDm** [comment]
@NachoAstro We added a demo with `Fragment`, check please here https://github.com/verygoodsecurity/vgs-collect-android/pull/634/files. Also, please make sure that the theme of your application or activity that holds fragment is set to Material in `AndroidManifest.xml`

**Comment by NachoAstro** [comment]
Nice, let me know when you merge this code

**Comment by DmytroDm** [comment]
@NachoAstro PR merged into develop.
