### ISSUE TITLE
Card numbers validation

### ISSUE THREAD

**Issue by shchurov** [verygoodsecurity/vgs-collect-android#64]
We tested regexes from [CardType.kt](https://github.com/verygoodsecurity/vgs-collect-android/blob/f6f633db7d6e53ec99190b52f76fdec6e9a040d8/vgscollect/src/main/java/com/verygoodsecurity/vgscollect/view/card/CardType.kt) on our collection of real BINs and found that about 5% of them fail. Does it mean that your SDK won't validate the cards with these BINs and won't allow submitting them?

Here's the collection:
[missed_android_bins.csv.zip](https://github.com/verygoodsecurity/vgs-collect-android/files/4729026/missed_android_bins.csv.zip)

If the issue exists, can you please provide an ETA on fixing this? We're releasing a version with VGS support very soon and the issue can have a huge impact on us.

**Comment by Endorf** [comment]
Hi,
 Our SDK supports only brands from [CardType.kt](https://github.com/verygoodsecurity/vgs-collect-android/blob/f6f633db7d6e53ec99190b52f76fdec6e9a040d8/vgscollect/src/main/java/com/verygoodsecurity/vgscollect/view/card/CardType.kt) according to the regexes.
Android SDK has the ability to add your own card Brands if they are absent on the list.

```
cardNumberField.addCardBrand(CustomCardBrand("regex", "brand_name", R.drawable.brand_icon))
```
This mechanism allows you to add any local brands and validate them.

**Comment by shchurov** [comment]
We've got quite a few of those brands missing, is there any way to disable the validation?
We tried to use a very generic brand (like `\d+`) but it suppresses the rest of the brands with their icons.

**Comment by Endorf** [comment]
It is not possible to disable validation. 
The `\d+` will not work. At least it will make the detection of all other brands with more specific regexes impossible. The best practice would be if you set up detailed regex for **BIN** numbers of the local bank or subbrand(For example [VISA](https://github.com/verygoodsecurity/vgs-collect-android/blob/f6f633db7d6e53ec99190b52f76fdec6e9a040d8/vgscollect/src/main/java/com/verygoodsecurity/vgscollect/view/card/CardType.kt#L57) and [VISA electron](https://github.com/verygoodsecurity/vgs-collect-android/blob/f6f633db7d6e53ec99190b52f76fdec6e9a040d8/vgscollect/src/main/java/com/verygoodsecurity/vgscollect/view/card/CardType.kt#L25)).

I see only one way to manage those brands - to set up Regex:

```
cardNumberField.addCardBrand(CustomCardBrand("^123456", "brand_name_1", R.drawable.brand_icon))
cardNumberField.addCardBrand(CustomCardBrand("^654321", "brand_name_2", R.drawable.brand_icon))
cardNumberField.addCardBrand(CustomCardBrand("^321123", "brand_name_3", R.drawable.brand_icon))
```
or
```
cardNumberField.addCardBrand(CustomCardBrand("^(123456)|(654321)|(321123)", "brand_name", R.drawable.brand_icon))
 ```
Could you give us more details about your card brands which you cannot handle? 
- which length do they have?
- How many digits are sensitive?
- How many digits contains the secret code of those brands?
- or any other information which may help to resolve your issue.

If some information could be sensitive, please send it on the mail support@verygoodsecurity.com.

**Comment by shchurov** [comment]
Unfortunately, the BINs that I mentioned in the original post is all we have 😞 
It seems that our best option would be to figure out a common pattern for them and add it as a custom brand. Thanks anyways!

**Comment by Endorf** [comment]
Hi again,
The next week, we going to push a new release. We will change behavior in android SDK for `isRequared` a little bit. `IsRequired=false` will allow you to submit any data from field. At the same time, you will be able to track the real state of the field in OnStateChangeListener
