### ISSUE TITLE
Compose ExpirationDateEditTextWrapper setDateRegex not working

### ISSUE THREAD

**Issue by oteljazouli-bc** [verygoodsecurity/vgs-collect-android#649]
**Describe the bug**
```
ExpirationDateEditTextWrapper(
    collect = vgsForm,
    fieldName = CARD_EXP_DATE_FIELD_NAME,
    modifier = Modifier.fillMaxWidth(),
    onViewCreate = { inputLayout, editText: ExpirationDateEditText ->
        editText.setDatePickerMode(mode = DatePickerMode.INPUT)
        editText.setDateRegex("MM/yy")
    }
)
```
when setting `setDateRegex` it wont update and remain the preset MM/yyyy and so the validation always fails

**To Reproduce**
Simply use the code above

**Expected behavior**
DateRegex should be applied

**Screenshots**

**Environment (please complete the following information):**
 - SDK Version 1.9.0
 - Android Version: any
 - Device: any

**Additional context**
I cant use 1.9.1 because of compose dependency being newer than the app version, but there is nothing in the changelog mentioning this fix

**Possible Solution**
`updateTimeGapsValidator` should be called, it is not called when the regex is updated and so ` timeGapsValidator = TimeGapsValidator(` will remain as the instance with MM/yyyy 

thanks

**Comment by DmytroDm** [comment]
@oteljazouli-bc Thank you for providing the details. We will investigate it and let you know the results.

**Comment by DmytroDm** [comment]
@oteljazouli-bc Hi, the new version 1.9.3 released, try this one and let us know if the bug is fixed for you.
Release notes https://github.com/verygoodsecurity/vgs-collect-android/releases/tag/v1.9.3
