### ISSUE TITLE
VGSCardNumberEditText does not support horizontal scrolling when text exceeds the view width

### ISSUE THREAD

**Issue by ndco** [verygoodsecurity/vgs-collect-android#686]
**Describe the bug**
VGSCardNumberEditText does not scroll horizontally when the input text exceeds the width of the view. This behavior is inconsistent with VGSEditText, which correctly supports horizontal scrolling under the same conditions.

**To Reproduce**
```
        val textInputLayout = VGSTextInputLayout(reactContext)
        val cardNumberEditText = VGSCardNumberEditText(reactContext)

        // Set properties for horizontal scrolling
        cardNumberEditText.isSingleLine = true
        cardNumberEditText.setHorizontalScrollBarEnabled = true
        
        // Additional properties to handle scrolling behavior
        cardNumberEditText.setPadding(0, 0, 0, 0)
        cardNumberEditText.gravity = Gravity.CENTER_VERTICAL
        
        textInputLayout.addView(cardNumberEditText, ViewGroup.LayoutParams(
                ViewGroup.LayoutParams.MATCH_PARENT,
                ViewGroup.LayoutParams.WRAP_CONTENT
        ))
        return textInputLayout
```

**Expected behavior**
VGSCardNumberEditText should scroll horizontally when the input text exceeds the view width, similar to the behavior of VGSEditText.

**Screenshots**
N/A

**Environment (please complete the following information):**
 - SDK Version: 1.7.2
 - Android Version: 13
 - Device: Pixel 8a

**Additional context**
N/A

**Possible Solution**
N/A

**Comment by DmytroDm** [comment]
@ndco Thank you for informing us about this issue. We will have a look at this.

**Comment by DmytroDm** [comment]
@ndco I have investigated the issue and found out this is the react-native issue. You can check the issue thread [here](https://github.com/facebook/react-native/issues/4990). As a workaround for this, I can suggest force layout invalidation after the view state change like this:

```kotlin
 override fun createViewInstance(reactContext: ThemedReactContext): VGSTextInputLayout {
        val textInputLayout = VGSTextInputLayout(reactContext)
        val cardNumberEditText = VGSCardNumberEditText(reactContext)

        cardNumberEditText.setOnFieldStateChangeListener(object : OnFieldStateChangeListener {

            override fun onStateChange(state: FieldState) {
                invalidateView(cardNumberEditText)
                invalidateView(textInputLayout)
            }
        })
            ...
    }

    private fun invalidateView(view: View) {
        view.post {
            view.measure(
                View.MeasureSpec.makeMeasureSpec(
                    view.width,
                    View.MeasureSpec.EXACTLY
                ),
                View.MeasureSpec.makeMeasureSpec(
                    view.height,
                    View.MeasureSpec.EXACTLY
                )
            )
            view.layout(view.left, view.top, view.right, view.bottom)
        }
    }
```

**Comment by ndco** [comment]
Hi @DmytroDm - thanks for the update!
Yes the guide you have provide did resolve my issue.

Thank you so much for looking into this! Much appreciated 🙏
